spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dms
      username: demouser
      password: secret
      authentication-database: dms
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

server:
  port: 7070
  jetty:
    threads:
      min: 128
      max: 128
  servlet:
    context-path: /api
    session:
      timeout: 220m

app:
  fileStore:
    baseFolder: "/home/palmyra/Desktop/"
  fileResource:
    templateFolder: "templates"
    stampFolder: "fixedStamps"

aws:
  s3:
    bucketName: hpcbucket
    region: ap-south-1
    accessKey: AKIAIOSFODNN7EXAMPLE
    secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    endpoint: http://192.168.1.11:9000
    corePoolSize: 25
    maximumPoolSize: 25
    keepAliveTime: 600
    workQueue: 25
    maxConcurrency: 32
